language: java

services:
  - docker
env:
  global:
    - secure: "encrypted-dockerhub-username"
    - secure: "encrypted-dockerhub-password"

script:
  - cd dark-sky
  - mvn clean install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=athiraks/dark-sky
  - docker build -t $IMAGE_NAME:$TAG .
  - docker push $IMAGE_NAME:$TAG

